services:
  - type: web
    name: soil-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
